### ISSUE TITLE
ACS712 if it is possible

### ISSUE THREAD

**Issue by okanduzyel** [maccoylton/esp-homekit-power-monitor#1]
Hi, 

SCT-013-000 is physically the too big and more expensive solution instead of ACS712. Do you think to replace it with ACS712 if is possible? Besides, Could you combine it with a power outlet?

**Comment by maccoylton** [comment]
Should be possible although I don't current have one available to build to build or test.   I've ordered one of ebay, should be here next week. BTW if you want a power monitoring outlet, then look at my repository https://github.com/maccoylton/esp-homekit-gosund-up111

**Comment by okanduzyel** [comment]
HLW8012 is not a good solution for that because it is rare and a little expensive. I highly recommend using ACS712.
