### ISSUE TITLE
Custom characters

### ISSUE THREAD

**Issue by kiralikbeyin** [maccoylton/esp-homekit-power-monitor#2]
`  HOMEKIT_SERVICE(SWITCH, .primary=true, .characteristics=(homekit_characteristic_t*[]){

            HOMEKIT_CHARACTERISTIC(NAME, "Switch"),
            &switch_on,
            &volts,
            &watts,
            &amps,
            &ota_trigger,
            &wifi_reset,
            &ota_beta,
            &lcm_beta,
            &task_stats,
            &wifi_check_interval,
            NULL
`

I coulnt understand &volts, &watts ... 

Can i see in home app or in other apps like eve?

Please can you send a screenshot if possible..

**Comment by maccoylton** [comment]
Custom characteristics don't show in the home app, but so show in the Eve app.
