### ISSUE TITLE
Not Pairing with 111-11-111

### ISSUE THREAD

**Issue by Techposts** [maccoylton/esp-homekit-power-monitor#4]
I tried connecting to Homekit but it's not connecting with 111-11-111
![image](https://user-images.githubusercontent.com/28442414/165784011-3d4da4d3-6616-439b-8cb6-7d61eb51e0c0.png)

**Comment by maccoylton** [comment]
Are you compiling from source or using the pre compiled binary

**Comment by maccoylton** [comment]
Close as no further reponse so assume issue wsa resovled
